### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jisungbin** [duckie-team/quack-quack-android#500]
## Ir

- [ ] Supports more SugarToken types
- [ ] Supports functional types of parameters

## Test

- [ ] buildSrc logics
- [ ] SugarToken errors
- [ ] `core-aide`
- [x] `core-sugar-processor-kotlinc`에서 `Ir` 테스트와 `poet` 테스트 개별 클래스로 분리

**Comment by jisungbin** [comment]
#### TODO 관리 방식 변경
